# Generated by Django 5.2.1 on 2025-05-23 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dltik', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='page',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='page',
            name='ext',
        ),
    ]
