# Generated by Django 5.2.1 on 2025-05-27 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dltik', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='upload',
            name='final_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
