# Generated by Django 5.2.1 on 2025-05-15 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dltik', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PinnedArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pinned_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of precedence. Smaller numbers will appear first.')),
                ('note', models.CharField(blank=True, help_text='Internal notes if needed.', max_length=255)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pinned', to='dltik.article')),
            ],
            options={
                'ordering': ['order', '-pinned_at'],
            },
        ),
    ]
