# Generated by Django 5.2.1 on 2025-06-02 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dltik', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='download_count',
            new_name='downloads',
        ),
    ]
