# Generated by Django 5.2.1 on 2025-05-29 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dltik', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='type',
            field=models.CharField(choices=[('video', 'Video'), ('image', 'Image'), ('music', 'Music')], max_length=10),
        ),
    ]
