# Generated by Django 5.2.1 on 2025-05-15 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dltik', '0002_pinnedarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='show_toc',
            field=models.BooleanField(default=True, help_text='Show list automatically if there is title?'),
        ),
    ]
