# Generated by Django 5.2.1 on 2025-05-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dltik', '0002_alter_page_unique_together_remove_page_ext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='url',
            field=models.URLField(max_length=2000),
        ),
    ]
