# Generated by Django 5.2.1 on 2025-05-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dltik', '0002_file_download_count_upload_final_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='filename',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
