# Generated by Django 5.2.1 on 2025-05-30 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dltik', '0003_thumbnail_article_thumb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='thumb',
        ),
        migrations.AddField(
            model_name='article',
            name='thumbnails',
            field=models.ManyToManyField(related_name='articles', to='dltik.thumbnail'),
        ),
    ]
