# Generated by Django 5.2.1 on 2025-05-27 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dltik', '0003_file_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='download_count',
            field=models.IntegerField(default=-1),
        ),
    ]
