# Generated by Django 5.2.1 on 2025-06-08 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dltik', '0003_remove_page_format_remove_page_slug_page_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='format',
            field=models.CharField(choices=[('html', 'HTML'), ('text', 'Plain Text'), ('json', 'JSON')], default='html', max_length=10),
        ),
    ]
