# Generated by Django 5.2.1 on 2025-05-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dltik', '0004_tag_remove_article_tags_article_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='show_meta',
            field=models.BooleanField(default=True, help_text='Enable if you want to display poster information and creation time'),
        ),
    ]
