# Generated by Django 5.2.1 on 2025-05-27 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dltik', '0004_alter_file_download_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='download_count',
            field=models.IntegerField(default=0),
        ),
    ]
