# Generated by Django 5.2.1 on 2025-05-30 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dltik', '0004_remove_article_thumb_article_thumbnails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='cover_image',
        ),
    ]
