# Generated by Django 5.2.1 on 2025-05-27 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dltik', '0005_alter_file_download_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='media_type',
        ),
        migrations.AddField(
            model_name='file',
            name='cookies',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='type',
            field=models.CharField(choices=[('video', 'Video'), ('photo', 'Photo')], default='photo', max_length=10),
            preserve_default=False,
        ),
    ]
