# Generated by Django 5.2.1 on 2025-06-11 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dltik', '0005_alter_article_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='summary',
            new_name='description',
        ),
    ]
