# Generated by Django 5.2.1 on 2025-05-26 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dltik', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='allow_comments',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='show_meta',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='show_toc',
            field=models.BooleanField(default=True),
        ),
    ]
