# Generated by Django 5.2.1 on 2025-06-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dltik', '0008_systemlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='headers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='thumbnails',
            field=models.ManyToManyField(blank=True, related_name='articles', to='dltik.mediaasset'),
        ),
    ]
