# Generated by Django 5.2.1 on 2025-06-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dltik', '0009_file_headers_alter_article_thumbnails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='thumbnail',
            field=models.URLField(blank=True, max_length=3000, null=True),
        ),
    ]
