# Generated by Django 5.2.1 on 2025-06-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dltik', '0010_alter_upload_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='label',
            field=models.CharField(max_length=255),
        ),
    ]
